version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cart_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cart_db
      MYSQL_USER: cart_user
      MYSQL_PASSWORD: cart_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: